---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: hostname
  name: hostname
  namespace: '${ parameters.namespace ?: staging }'
  annotations:
    app: hostname
    owner: stephen
    otherAnnotation: testValue
spec:
  ports:
  - port: 443 #80
    protocol: TCP
    targetPort: 443 #80
  selector:
    app: hostname
  sessionAffinity: None
  type: LoadBalancer

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: hostname
  name: hostname-metrics
  namespace: '${ parameters.namespace ?: staging }'
  annotations:
    app: hostname
    owner: stephen
    otherAnnotation: testValue
spec:
  ports:
  - port: 9113
    protocol: TCP
    targetPort: 9113
    name: metrics
  selector:
    app: hostname
  sessionAffinity: None
  type: ClusterIP
     
   
