---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: hostname
  name: hostname
  namespace: '${ parameters.namespace ?: staging }'
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80    
  - port: 9113
    protocol: TCP
    targetPort: 9113
    name: metrics
  selector:
    app: hostname
  sessionAffinity: None
  type: LoadBalancer
